name: Run Go Files

on:
  push:
    paths:
      - '**.go'

jobs:
  run-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # or your preferred version

      - name: Run main Go file(s)
        run: |
          for file in $(find . -name "*.go" -type f); do
            echo "Running $file"
            go run "$file"
          done
